name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  docker:
    name: Build on Linux and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: avsm/eeww:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  mac:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deps
        run: brew install cmake gmp capnp
      -
        name: Build
        run: env DUNE_PROFILE=dev make
  nix:
    name: Build with Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v12
      - run: nix --extra-experimental-features "nix-command flakes" build
